name: Compiling and running a java file

on: [push]

jobs:
  compile-and-run-javasetup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - run: java HelloWorldApp.java
  
  print-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print out content on compile java file
      run: cat compile-javafile
  
